/*
 * Copyright (C) 2019-2024 LitterBox contributors
 *
 * This file is part of LitterBox.
 *
 * LitterBox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * LitterBox is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with LitterBox. If not, see <http://www.gnu.org/licenses/>.
 */
package de.uni_passau.fim.se2.litterbox.analytics.llm;

import de.uni_passau.fim.se2.litterbox.JsonTest;
import de.uni_passau.fim.se2.litterbox.analytics.Issue;
import de.uni_passau.fim.se2.litterbox.analytics.bugpattern.BlockingIfElse;
import de.uni_passau.fim.se2.litterbox.ast.ParsingException;
import de.uni_passau.fim.se2.litterbox.ast.model.Program;
import de.uni_passau.fim.se2.litterbox.ast.visitor.ScratchBlocksVisitor;
import de.uni_passau.fim.se2.litterbox.llm.DummyLlmApi;
import de.uni_passau.fim.se2.litterbox.llm.prompts.LlmPromptProvider;
import de.uni_passau.fim.se2.litterbox.llm.prompts.QueryTarget;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.Collections;
import java.util.Set;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.assertAll;

class LLMIssueEffectExplainerTest implements JsonTest {

    @Test
    void explainEffect() throws ParsingException, IOException {
        final Program program = getAST("src/test/fixtures/bugpattern/blockingIfElse.json");
        final Set<Issue> issues = new BlockingIfElse().check(program);
        assertThat(issues).isNotEmpty();

        final DummyLlmApi api = new DummyLlmApi(Collections.nCopies(issues.size(), "new hint generated by the LLM"));
        final LLMIssueEffectExplainer processor = new LLMIssueEffectExplainer(
                api, LlmPromptProvider.get(), new QueryTarget.SpriteTarget("Figur1")
        );
        final Set<Issue> processedIssues = processor.apply(program, issues);

        assertThat(processedIssues).hasSize(issues.size());
        assertAll(processedIssues.stream()
                .map(issue -> () -> {
                    // should contain both original hint and additional explanation
                    assertThat(issue.getHintText()).contains("[b]Problem:[/b]");
                    assertThat(issue.getHintText()).contains("[newLine][b]LLM");
                    assertThat(issue.getHintText()).contains("new hint generated by the LLM");
                })
        );

        assertThat(api.getRequests().getFirst()).contains(ScratchBlocksVisitor.SPRITE_MARKER + " Figur1");
    }

    @Test
    void explainEffectBulletPointList() throws ParsingException, IOException {
        final Program program = getAST("src/test/fixtures/bugpattern/blockingIfElse.json");
        final Set<Issue> issues = new BlockingIfElse().check(program);
        assertThat(issues).isNotEmpty();

        final DummyLlmApi api = new DummyLlmApi(Collections.nCopies(issues.size(), """
                Explanation:

                1. First effect.
                2. Other explanation.
                42. Even more explanation.
                """.stripIndent()));
        final LLMIssueEffectExplainer processor = new LLMIssueEffectExplainer(
                api, LlmPromptProvider.get(), new QueryTarget.SpriteTarget("Figur1")
        );
        final Set<Issue> processedIssues = processor.apply(program, issues);

        assertThat(processedIssues).hasSize(issues.size());
        assertAll(processedIssues.stream()
                .map(issue -> () -> {
                    assertThat(issue.getHintText()).contains("[newLine]1. First effect.");
                    assertThat(issue.getHintText()).contains("[newLine]2. Other explanation.");
                    assertThat(issue.getHintText()).contains("[newLine]42. Even more explanation.");
                })
        );
    }

}
