/*
 * Copyright (C) 2019-2022 LitterBox contributors
 *
 * This file is part of LitterBox.
 *
 * LitterBox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * LitterBox is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with LitterBox. If not, see <http://www.gnu.org/licenses/>.
 */
package de.uni_passau.fim.se2.litterbox.ast.util;

import de.uni_passau.fim.se2.litterbox.ast.Constants;
import de.uni_passau.fim.se2.litterbox.ast.model.ActorDefinition;
import de.uni_passau.fim.se2.litterbox.ast.model.Program;
import de.uni_passau.fim.se2.litterbox.ast.model.ScriptEntity;
import de.uni_passau.fim.se2.litterbox.ast.visitor.ScriptEntityNameVisitor;

import java.util.Optional;

public class NodeNameUtil {
    private NodeNameUtil() {
        throw new IllegalCallerException("utility class constructor");
    }

    /**
     * Checks if the actor has a default name that was generated upon actor creation by Scratch itself.
     *
     * <p>A default name is a translation of ‘sprite’ ({@link Constants#DEFAULT_SPRITE_NAMES}), followed by a number.
     *
     * @param actor Some actor.
     * @return True, if the actor has an automatically generated name.
     */
    public static boolean hasDefaultName(final ActorDefinition actor) {
        // no special replacements except removal of the numbers needed: if the non-numeric part is not in the list of
        // known default names, it is not a default name
        final String spriteName = actor.getIdent().getName().toLowerCase().replaceAll("\\d+", "");
        return isDefaultName(spriteName);
    }

    /**
     * Checks if a normalized sprite name is one of the default names.
     *
     * @param normalisedSpriteLabel A <emph>normalised</emph> sprite name.
     * @return If the name is a default name generated by Scratch.
     */
    private static boolean isDefaultName(final String normalisedSpriteLabel) {
        return Constants.DEFAULT_SPRITE_NAMES.contains(normalisedSpriteLabel);
    }

    /**
     * Builds a globally unique name for a script.
     *
     * <p>Combines the name/projectID of the program with the unique name of a script to create a globally unique
     * identifier for the script.
     *
     * @param program The program the script belongs to.
     * @param scriptEntity Some script inside {@code program}.
     * @return A unique name based on the program and script ids. Empty if no ID could be generated for the script.
     */
    public static Optional<String> getScriptEntityFullName(Program program, ScriptEntity scriptEntity) {
        return ScriptEntityNameVisitor.getScriptName(scriptEntity)
                .map(name -> program.getIdent().getName() + "_" + name);
    }
}
